### ISSUE TITLE
message.MessageDisconnect.REASON.ProtocolVersion builtins.AttributeError: type object 'MessageDisconnect' has no attribute 'REASON'

### ISSUE THREAD

**Issue by ggruszczynski** [golemfactory/golem-messages#28]
```
CRITICAL [twisted                            ] Unhandled Error
Traceback (most recent call last):
  File "/home/ggruszczynski/.virtualenvs/golem-env/lib/python3.5/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/ggruszczynski/.virtualenvs/golem-env/lib/python3.5/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/ggruszczynski/.virtualenvs/golem-env/lib/python3.5/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/ggruszczynski/.virtualenvs/golem-env/lib/python3.5/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/ggruszczynski/.virtualenvs/golem-env/lib/python3.5/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/ggruszczynski/.virtualenvs/golem-env/lib/python3.5/site-packages/twisted/internet/tcp.py", line 208, in doRead
    return self._dataReceived(data)
  File "/home/ggruszczynski/.virtualenvs/golem-env/lib/python3.5/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/ggruszczynski/.virtualenvs/golem-env/lib/python3.5/site-packages/twisted/internet/endpoints.py", line 119, in dataReceived
    return self._wrappedProtocol.dataReceived(data)
  File "/home/ggruszczynski/PycharmProjects/another_golem/golem/network/transport/tcpnetwork.py", line 482, in dataReceived
    self._interpret(data)
  File "/home/ggruszczynski/PycharmProjects/another_golem/golem/network/transport/tcpnetwork.py", line 514, in _interpret
    self.session.interpret(m)
  File "/home/ggruszczynski/PycharmProjects/another_golem/golem/network/p2p/peersession.py", line 114, in interpret
    BasicSafeSession.interpret(self, msg)
  File "/home/ggruszczynski/PycharmProjects/another_golem/golem/network/transport/session.py", line 88, in interpret
    action(msg)
  File "/home/ggruszczynski/PycharmProjects/another_golem/golem/network/p2p/peersession.py", line 346, in _react_to_hello
    message.MessageDisconnect.REASON.ProtocolVersion
builtins.AttributeError: type object 'MessageDisconnect' has no attribute 'REASON'
```

**Comment by jiivan** [comment]
What version of golem_messages?

**Comment by ggruszczynski** [comment]
I launched develop. In requirements.txt:
-e git://github.com/golemfactory/golem-messages.git@v1.1.0#egg=golem_messages

**Comment by jiivan** [comment]
Can you verify with newest develop (golem messages v1.1.1)?

**Comment by ggruszczynski** [comment]
It is OK on golem messages v1.1.1.
